# Generated by Django 4.2.4 on 2023-08-22 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=12)),
                ('fname', models.CharField(default='', max_length=12)),
                ('phone', models.CharField(default='', max_length=12)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('text', models.TextField(default='')),
            ],
            options={
                'db_table': 'our_model',
            },
        ),
        migrations.CreateModel(
            name='ModelWithTranslator',
            fields=[
                ('ourmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='box.ourmodel')),
            ],
            bases=('box.ourmodel',),
        ),
    ]
